### ISSUE TITLE
Pydantic

### ISSUE THREAD

**Issue by clbarnes** [elliot-100/Spond-classes#93]
I'd recommend looking into pydantic. It handles the parsing for you, gives very informative validation errors, and is fast.

**Comment by elliot-100** [comment]
Yes I recently realised that... starting from scratch was useful as a learning exercise though.

**Comment by clbarnes** [comment]
Fair enough!

**Comment by elliot-100** [comment]
Now done! https://github.com/elliot-100/Spond-classes/releases/tag/v0.9.0

Thanks for the push.
